[package]
name = "wam_macros"
version = "0.1.0"
edition = "2021"
authors = ["ThePoultryMan"]
license = "GPL-3.0"
repository = "https://github.com/ThePoultryman/WAM"

[lib]
proc-macro = true

[dependencies]
darling = "0.20.10"
proc-macro2 = "1.0.86"
quote = "1.0.36"
syn = "2.0.72"
