[package]
name = "wam_macros"
version = "0.1.0"
edition = "2021"
authors = ["ThePoultryMan"]
license = "GPL-3.0"
repository = "https://github.com/ThePoultryman/WAM"

[lib]
proc-macro = true

[dependencies]
